[package]
name = "documentation_scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
kuchiki = "0.8.1"
lopdf = "0.34.0"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking"] }
tokio = { version = "1.40.0", features = ["full"] }
